# Use root/example as user/password credentials
version: "3.7"
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db-volume:/var/lib/mysql
    environment:
      MYSQL_USER: wordpressdev
      MYSQL_PASSWORD: wordpressdev
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: devpassword
  wordpress:
#    build:
#        context: ./
#        dockerfile: Dockerfile
    image: tippexs/nginxspace:latest
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ../wordpress:/var/apphome/wordpress
      - ../api:/var/apphome/api
      - ../vendor:/var/apphome/vendor
    ports:
      - 80:8080
      - 85:8081
