# Use root/example as user/password credentials
version: "3.7"
services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - 80:80
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db-volume:/var/lib/mysql
    environment:
      MYSQL_USER: wordpressdev
      MYSQL_PASSWORD: wordpressdev
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: devpassword
  unitappserv:
#    build:
#        context: ./
#        dockerfile: Dockerfile
    image: tippexs/nginxspace:latest
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ../wordpress:/var/apphome/wordpress
      - ../pythonapp:/var/apphome/python
      - ../app1:/var/apphome/app1
      - ../app2:/var/apphome/app2
      - ../vendor:/var/apphome/vendor
    ports:
      - 8100:8080
      - 8000:8000
      - 9000:9000
